version: '3'

services: 

  app-desafio:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: app-desafio
    entrypoint: dockerize -wait tcp://db-desafio:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - desafio_2
    volumes:
      - ./nodejs/app/:/usr/src/app/
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db-desafio

  db-desafio:
    image: mysql:5.7
    command:  --innodb-use-native-aio=0
    container_name: db-desafio
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio_2

  nginx-desafio: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-desafio
    networks: 
      - desafio_2
    ports:
      - "80:80"
    depends_on:
      - app-desafio

networks: 
  desafio_2:
    driver: bridge